apiVersion: v1
kind: DeploymentConfig
metadata:
  name: dc-v1.2
  resourceVersion:
  selflink: 
  uid: 
  managedfield: []
  # namespace: katmandu25-santander-phpinfo Lo quitamos porque asi no falla al importarlo desde otro proyecto.
spec:
  replicas: 2
  selector:
    app: santander-phpinfo
  template:
    metadata:
    #  name: hello-openshift  Este nombre lo elige de forma aleatoria. No vale.
      labels:
        app: santander-phpinfo
      creationTimestamp: null
    spec:
      containers:
        - name: php
          image: 'index.docker.io/katmandu25/santander-phpinfo:1.1'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: nombre_alumno
              value: katmandu25
          resources:  # Si no lo configuramos nos pueden machacar el contenedor
            limits:  # Buena practica poner limit = request para evitar overcommit. 
              cpu: 40m
              memory: 40M
            requests:  # Es lo m√≠nimo con lo que arranca el contenedor
              cpu: 20m
              memory: 20M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always  # Afecta al POD
      securityContext: {}
      schedulerName: default-scheduler
status: {}
